### ISSUE TITLE
How did you get the object proposals?

### ISSUE THREAD

**Issue by IssamLaradji** [Cyanogenoid/vqa-counting#10]
I love the paper, thanks for the code! 

How did you obtain the object proposals? I see that you referenced Anderson et al. 2017 paper [1], does that mean the object proposals are from their Faster-RCNN?  On which dataset was Faster-RCNN trained on?

Thanks!

[1] http://openaccess.thecvf.com/content_cvpr_2018/CameraReady/1163.pdf

**Comment by Cyanogenoid** [comment]
Correct, the object proposals come from Anderson et al., you can find downloads in their repository at https://github.com/peteanderson80/bottom-up-attention#pretrained-features

They trained their R-CNN on Visual Genome https://visualgenome.org/.
