### ISSUE TITLE
Connected Computation Graph 

### ISSUE THREAD

**Issue by aribornstein** [Cyanogenoid/vqa-counting#2]
This is a very cool I have a project. I'm working on a similar project where I need to count instances of objects in a given set of objects in an image. 

My current naive approach just uses a trained Retina-net model but suffers from the duplications mentioned in your paper. I would like to hopefully improve my model by linking the existing  computation graph of retinanet to the counting module you have written. Currently my model is based off of [this implementation of retinanet](https://github.com/fizyr/keras-retinanet). 

My project isn't a VQA scenario i.e I don't need to do any seq2seq on a query string, i just need to count objects but I still think this is relevant. Is this something you have already done? Can you recommend a pytorch implementation of retina net that works well with your code? Or if possible include an example of how to do this?

Thank you.

**Comment by Cyanogenoid** [comment]
I haven't worked with RetinaNet, but it should be possible to use the counting component with it. The important bit is to tell it what proposals are relevant with a score from 0 to 1. In the paper, this is done with an attention model conditioned on the question, which you would want to replace with the probability of each bounding box, determined by the RetinaNet.

I imagine that the set-up would look like this:
Image ---[RetinaNet]---> bounding boxes, probability of each box ---[counting component]---> count

A relatively simple thing to get started is to take your existing model in Keras, get bounding boxes and probabilities for each bounding box out of it, and just feed those into the counting component. If the counting component seems to help, then you can use find a RetinaNet in PyTorch and do end-to-end training.

**Comment by aribornstein** [comment]
Thank you this is exactly what I had in mind. Again really great work. I enjoyed the article and your response to the reviewers. I will update you later in the month with how my experiments proceed. When you trained this did you get you use an end to end computation graph with the object detection component, or did you run the counting component individually?

**Comment by Cyanogenoid** [comment]
In the VQA experiments, it was trained end-to-end. This is necessary in VQA, since there is no ground-truth set of relevant bounding boxes for a question, so there is no supervisory information for a two-stage approach. In the toy dataset experiments, the score of each bounding box is given as input, so I suppose that could be considered similar to the two-stage approach.
