### ISSUE TITLE
Downloading bottom-up attention data  403 Forbidden error 

### ISSUE THREAD

**Issue by gicheonkang** [Cyanogenoid/vqa-counting#3]
Downloading bottom-up attention data  403 Forbidden error..
Is there any source that I can download with command line?

**Comment by Cyanogenoid** [comment]
Looks like the bottom-up attention authors' hosting doesn't work anymore (tracked in https://github.com/peteanderson80/bottom-up-attention/issues/31). If they haven't fixed it after I've returned from ICLR at the end of the week, I'll see whether I can host the features myself.

**Comment by peteanderson80** [comment]
The links in the [bottom-up-attention repo](https://github.com/peteanderson80/bottom-up-attention/blob/master/README.md) have been updated. Please use the new links.
