### ISSUE TITLE
baseline model without counting

### ISSUE THREAD

**Issue by jayleicn** [Cyanogenoid/vqa-counting#4]
A quick question, to obtain the baseline model without counting module, we only need to delete the counting.Counter() part and modify the classifier in model.py, right?

**Comment by Cyanogenoid** [comment]
Yep! The simplest way is to just delete the line in the classifier that uses the counting features, which still runs the counting module but ignores its features. If you want to get rid of the counting module completely, you have to delete it from the Net module and also delete the call to it, as you said.

**Comment by jayleicn** [comment]
Great! Thanks!
