### ISSUE TITLE
Training clarification

### ISSUE THREAD

**Issue by correiav** [Cyanogenoid/vqa-counting#7]
Hi @Cyanogenoid ! 
First of all many thanks for sharing your great work!
I'm currently training the model using the `train.py` command. I see the training alternates between train and val sets, as you mentioned in the repo. The info below is what I can see from the command line:
`train E000: 100% 1698/1698 [17:03<00:00,  1.66it/s, acc=0.4774, loss=1.9324]` and
`val E000: 100% 838/838 [03:40<00:00,  3.80it/s, acc=0.5126, loss=1.7152]`

What do the numbers 1698 and 838 refer to?

Thank you so much!

**Comment by Cyanogenoid** [comment]
Those are the number of mini-batches in training and validation respectively. If you multiply these numbers by the batch size 256, you (roughly) get the total number of training and validation examples.

**Comment by correiav** [comment]
Thank you so much for replying promptly! 
Just one more thing, would you have any advice on how to improve GPU usage? Because, apparently the training process is using very little go my GPU at the moment, please see below:
`Device 0 [PCIe 0:133:0.0]: GeForce GTX 1080 (CC 6.1): 6475.9 of 8191.8 MB (i.e. 79.1%) Free`
It's been a little over 4hs and only 10 epochs have run so far. And, I'm not sure if it's normal. 
Thank you once again.

**Comment by Cyanogenoid** [comment]
That does seem quite slow. Is your data on an SSD? Maybe it's limited by how quickly it can load the image features off the disk.
You can try using the 36 fixed features instead of the 100 adaptive features, see vqa-v2/README.md for instructions.

**Comment by correiav** [comment]
Yes, all data is on a SSD. I've already modified the config to use the 36 fixed features. In any case, thank you so much!

**Comment by Cyanogenoid** [comment]
Are things good now? Can this issue be closed?

**Comment by correiav** [comment]
Hi @Cyanogenoid !
Sorry for the late response. Sure, I'm closing the issue. I ended up decreasing the batch size from 256 to 128, after that the program run a bit faster on my machine. 
Thank you
