### ISSUE TITLE
Unable to find preprocess-images.py. Is it removed?

### ISSUE THREAD

**Issue by BhanuPhanindra** [Cyanogenoid/vqa-counting#8]
Also when I try to run python3 preprocess-features.py I'm getting the following error, Unable to open file (unable to open file: name = '/ssd/genome-trainval.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2). Where did I go wrong? Preprocess python codes are supposed to create these files, json is created in the same directory instead of .h5. Can some explain how to run this properly?
Thank you

**Comment by Cyanogenoid** [comment]
The config.py defaults to saving the file to /ssd, which fails if it doesn't exist. You can just change the line in config.py to save to the local directory instead. I'll change it so that it does that by default.

**Comment by Cyanogenoid** [comment]
If you `git pull` now, it should work. Note that a different change now requires pytorch 0.4.

**Comment by mkhalil1998** [comment]
Hello, still getting this error: OSError: Unable to open file (unable to open file: name = 'genome-trainval.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0). Should a h4 file called 'genome-trainval.h5' already exist? or should it create it? If so why is it giving this error?
Any help would be appreciated! Thank you
