### ISSUE TITLE
question about Piecewise Linear Activation Function

### ISSUE THREAD

**Issue by KaihuaTang** [Cyanogenoid/vqa-counting#9]
Hi~ I'm following your work recently. But I'm quite confused about some details, especially Piecewise Linear Activation Function. How does its weight Parameters be updated through gradient? Since the count feature is been transferred to the one-hot presentation, will this operate cut off the backpropagation?

**Comment by Cyanogenoid** [comment]
The count features are a linear interpolation of two one hot vectors, and the weighting on this interpolation is differentiable. E.g. the encoding of an output of c=1.25 is [0 0.75 0.25 0 0 ...] and a slight change away from 1.25 will also change the encoding slightly. That means that c is differentiable, so you can differentiate wrt the weights in the piecewise linear activation too.
